# Generated by Django 4.2.7 on 2026-07-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_set_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Belgilansa, foydalanuvchi saytda maqola yoza oladi (admin panelsiz).', verbose_name='Muallif'),
        ),
    ]
