# Generated by Django 4.2.7 on 2026-03-01 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon (CSS class yoki emoji)')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Rang (hex)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('content_type', models.CharField(choices=[('article', 'Maqola'), ('tutorial', 'Darslik'), ('video', 'Video darslik'), ('course', 'Kurs')], default='article', max_length=20, verbose_name='Tur')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Muqova rasmi')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Qisqacha tavsif')),
                ('content', models.TextField(verbose_name='Kontent (HTML)')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL (video uchun)')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Kutilmoqda'), ('published', 'Chop etilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name="O'qish vaqti (daqiqa)")),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Teglar (vergul bilan)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr vaqti')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
