# Generated by Django 4.2.7 on 2026-03-01 09:37

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Kontent (Markdown + LaTeX)'),
        ),
    ]
