# Generated by Django 4.2.7 on 2026-07-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism-familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('topic', models.CharField(max_length=300, verbose_name='Maqola mavzusi / sarlavhasi')),
                ('content_type', models.CharField(choices=[('article', 'Maqola'), ('tutorial', 'Darslik'), ('video', 'Video darslik'), ('course', 'Kurs')], default='article', max_length=20, verbose_name='Tur')),
                ('message', models.TextField(verbose_name="Qo'shimcha ma'lumot / reja")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_requests', to='articles.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola zayavkasi',
                'verbose_name_plural': 'Maqola zayavkalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
