# Generated by Django 4.2.7 on 2026-07-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ism-familiya'),
        ),
        migrations.AlterField(
            model_name='articlerequest',
            name='topic',
            field=models.CharField(blank=True, max_length=300, verbose_name='Maqola mavzusi / sarlavhasi'),
        ),
    ]
