# Generated by Django 4.2.7 on 2026-07-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articlerequest_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articlerequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='articlerequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='articlerequest',
            name='topic',
        ),
        migrations.AlterField(
            model_name='articlerequest',
            name='message',
            field=models.TextField(verbose_name="O'zi haqida"),
        ),
    ]
