# Generated by Django 6.0.1 on 2026-07-06 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Sessiya kaliti')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('path', models.CharField(max_length=500, verbose_name='Sahifa')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Havola manbasi')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='Brauzer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tashrif',
                'verbose_name_plural': 'Tashriflar (statistika)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'session_key'], name='analytics_p_created_da65ed_idx')],
            },
        ),
    ]
